/*
 ============================================================================
 Name        : Project-Euler-2.c
 Author      : kanurag
 Version     :
 Copyright   : Your copyright notice
 Description : Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 ============================================================================
 */

#include <stdio.h>
#include <stdlib.h>

int main(void) {

	int lastEvenTerm,maxLimit,firstEvenTerm,seconEvendTerm,kPlus2thTerm;
	long long sum=0;

	scanf("%d", &maxLimit);
	firstEvenTerm = 2;
	seconEvendTerm = 8;
	lastEvenTerm = 0;
	while (lastEvenTerm < maxLimit) {

		lastEvenTerm = 4 * seconEvendTerm + firstEvenTerm;


		firstEvenTerm=seconEvendTerm;
		seconEvendTerm=lastEvenTerm;

	}
// ....k,k+1,k+2,k+3....
// ....e,odd,odd,e....
//.....p.........p+1...
//F(k+2)=(Fe(p)+Fe(p+1))/2 where Fe(p+1) is last even term in even term sequence of fibonacci series
//
	kPlus2thTerm=(firstEvenTerm+seconEvendTerm)/2;




	//printf("LastEvenTerm=%d",lastEvenTerm);

	printf("\nSum=%d",(kPlus2thTerm-1)/2);


	return 0;
}
